### ISSUE TITLE
Notebook broken

### ISSUE THREAD

**Issue by tristanz** [simulacre7/tensorflow-study#1]
I was just playing around with your example code and noted that this line doesn't seem to work: 

```
mean = data['normalization'][0][0][0]
```

**Comment by simulacre7** [comment]
Hi, Tristan Zajonc

In my system, It works.
This statement is for handling matlab object
So please check your matlab model file(
http://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-verydeep-19.mat)
and related library(scipy.io)

Thank you.

2016-03-22 6:14 GMT+09:00 Tristan Zajonc notifications@github.com:

**Comment by tristanz** [comment]
Thanks.  It looks like I downloaded the wrong imagenet matrix.
